### ISSUE TITLE
Couldn't load "townfill.lev" / "village.lev" - making a maze.

### ISSUE THREAD

**Issue by transcendreamer** [elunna/hackem#142]
Windows binary, all default settings.

paniclog:
1.0.0-0 20221231 195351 1 -: impossible Couldn't load "townfill.lev" - making a maze.
1.0.0-0 20221231 195659 1 -: impossible Couldn't load "village.lev" - making a maze.

save file:
[zor.zip](https://github.com/elunna/hackem/files/10327690/zor.zip)

**Comment by elunna** [comment]
Town branch levels should load correctly for the windows binary now.
