### ISSUE TITLE
New vampires can't gain intrinsic telepathy from a floating eye?

### ISSUE THREAD

**Issue by transcendreamer** [elunna/hackem#161]
Is it correct and intended behavior? 

Vampires now only feed in battles and can't suck blood from corpses so that floating eyes grants no telepathy in any way?

Just tried attacking some floating eye now and no effect:

You smite the floating eye!  You bite the floating eye.  You feed on the lifeblood. The floating eye suddenly seems weaker!  The floating eye dies!

**Comment by elunna** [comment]
That is correct and intended yes.

The vampire race is now heavily "front loaded": So they start with all the resistances from SLASH'EM/UnNetHack + a couple extra:
* Sleep resistance
* Poison resistance
* Drain resistance
* Wither resistance
* Breathless
* Flying
* Regeneration

Death resistance will be added in the next release, it was omitted by mistake.
More info here: https://nethackwiki.com/wiki/Hack%27EM#Vampirics

In return for these advantages, not being able to get benefits from corpses is one of their key drawbacks. I'll leave this issue open for a while to hear other feedback.

**Comment by transcendreamer** [comment]
Thanks for detailed explanation! This was unexpected (to me) but actually looks very based and reasonable. 

Also I remember in dNethack tinning kits may be used to create potions of blood (in addition to canned meat) which were convenient for vampires to carry as a blood provision for hunger times... but probably this idea is not compatible with Hack'EM vampirism concept.

**Comment by elunna** [comment]
Thanks!  I'm still heavily experimenting and trying to improve on the vampire race. Not draining corpses and increasing their lifeblood nutrition came from SpliceHack - and I believe it was the right direction. Draining corpses is a pretty tedious task, and most of the time they go wasted anyway. But it also introduces a slew of bugs that are difficult and time-consuming to deal with. 

But I think it balances out the beginning strengths too. Vampirics will have to figure out telepathy (floating eyes), strength gain (giants), teleport control (tengu), teleportitis (nymphs/l), gaining levels (wraiths), and other things on their own. Plus they have to deal with late game vulnerability to fire in gehennom! It's kind of the opposite of tourists (a "back loaded" class).

**Comment by transcendreamer** [comment]
In connection with recently added dazzle ability 
( https://github.com/elunna/hackem/commit/33f05a89fb8512772fd1f614181baa3e0c1d7ae9 ) 
there could be also a biting ability - so that the vampire will need to dazzle his/her victim before enjoying blood of a paralyzed enemy - and this would be more realistic and interesting rather than auto-biting while fighting. Just thinking out loud. :)

**Comment by transcendreamer** [comment]
> dazzle
Probably not good idea because dazzle success depends on a variety of factors.
Vampires are similar to necromancers, who need to be close to the fallen victim in order to collect the spirit.
