### ISSUE TITLE
Fog/vapor cloud seeps through walls :)

### ISSUE THREAD

**Issue by transcendreamer** [elunna/hackem#165]
It looks questionably... bug?

![image](https://user-images.githubusercontent.com/46658406/212490026-e0ae9ee8-97b4-4aa9-9372-ad275e180b38.png)

**Comment by k21971** [comment]
Probably related, see https://github.com/k21971/EvilHack/commit/afed6410d23e1991db6ec22fe6dbf1aa81b5bdd4

**Comment by elunna** [comment]
This will be fixed in the next release. I changed vent placement so they won't appear next to walls.
