### ISSUE TITLE
Viewing spell effects from the casting menu

### ISSUE THREAD

**Issue by mariari** [elunna/hackem#189]
It would be nice to have a feature where I can press `?`, to start asking what spells mean. The necromancer role gets spells on level up, so the book can not be consulted for information about the spell.

**Comment by elunna** [comment]
Related features:
- [ ] Enable similar technique help

**Comment by elunna** [comment]
For the foreseeable future I don't see this getting implemented unless someone submits a PR for it. I do like the idea but I don't have the skills to design it yet.
