### ISSUE TITLE
whereis not working correctly

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#205]
<mobileuser> hackemslashem the whereis seems confused for 1.0?
<mobileuser> it said Noisytoot was on Chaotic Quest level: 6 whilst they were in sokoban

Reproduced in sokobon (on hdf)
<hackemslashem> !whereis hackemslashem
<Beholder> hackemslashem: [hdf-eu] hackemslashem [hackm]: (Ice Vam Mal Cha) T:1393 Chaotic Quest level: 6

Reported by mobileuser.

**Comment by k21971** [comment]
This is most likely a beholder bot problem, not Hack'EM. I may have the level listing incorrect in the bot settings.

**Comment by k21971** [comment]
This should be fixed now, fixed a couple things - beholder bot had the l/n/c quests represented incorrectly, and dgl was not unlinking the players .whereis file on exit.
