### ISSUE TITLE
end_burn: obj lightsaber not lit

### ISSUE THREAD

**Issue by transcendreamer** [elunna/hackem#215]
You descend the stairs.  You hear crashing rock.  You hear a lightsaber deactivate.
end_burn: obj lightsaber not lit
Program in disorder!  (Saving and reloading may fix this problem.)

Probably this problem comes from SlashTHEM. 
Game doesn't actually crash despite the message.

**Comment by elunna** [comment]
https://github.com/Soviet5lo/SlashTHEM/issues/54 looks almost exactly the same. I suspect a boulder filling a hole with a lightsaber and it's getting destroyed or turned off.

**Comment by elunna** [comment]
Reproducing:
Try 1: Create pit trap, wish for lightsaber, turn lightsaber on, drop lightsaber in pit. It automatically turns off.
Try 2: Create pit trap, wish for lightsaber, turn lightsaber on, eat glob of pudding so fingers get glibbery and weapon slips from hand. It still automatically turns off.
Try 3: Create pit trap, wish for lightsaber, create Aleax and give it the lightsaber. It lights it. Lure the Aleax onto the pit trap and killed it. The lightsaber still auto-turns off.
Try 4: Create a rolling boulder trap with a pit trap in the path of the boulder. Create a hill orc and give it a lightsaber. Lure the hill orc into the pit trap. Trigger the boulder trap so it fills the hole, kills the orc, and attempts to destroy the lightsaber while lit. Try 5: Let a lightsaber time down to a few charges left. Give it to a monster and let it deactivate in monster's possession.
No result: "The hill orc's red lightsaber (lit) (0) deactivates."
Try 6: Throw a lit lightsaber. This just results in the lightsaber auto-deactivating.

Success: Get a player with a lit wielded lightsaber to die and leave bones. Return to level of the bones. The lightsaber will deactivate on the first available turn, then causing the error.

**Comment by elunna** [comment]
@gebulmer I have a potential solution to this issue here (https://pastebin.com/ksEh4dC5) - would that work? On a couple tests it seems to be fine. I bypassed using the deactivate_lightsaber because it would print a message after death but also I got some weird "detached fork" crashes when the bones reloaded.
