### ISSUE TITLE
setting material of dwarvish spear to invalid material 14  Program in disorder!

### ISSUE THREAD

**Issue by transcendreamer** [elunna/hackem#228]
Message shows up just after the game start.
Inventory:
a +0 silver dwarvish spear (alternate weapon; not wielded)
Character: 
female dwarven Undead Slayer
Unix HackEM Version 1.1.0-0 Beta - last build Sun Mar  5 21:10:18 2023 
(221796dbfb986209e3c741195f0a5b2c23f8e27c,branch:master).

**Comment by elunna** [comment]
Thank you!  This was fixed in commit c0014000a.
