### ISSUE TITLE
Player monster Jedi are counted as Guardians (multi-variant)

### ISSUE THREAD

**Issue by Umbire** [elunna/hackem#248]
Crossposting from [SlashTHEM issue #101](https://github.com/Soviet5lo/SlashTHEM/issues/101):

Per [this line in monst.c](https://github.com/Soviet5lo/SlashTHEM/blob/d828e641d341175b5829bef070879bb163c7f636/src/monst.c#L6214) (which would be [L7435 here](https://github.com/elunna/hackem/blob/dev/src/monst.c#L7435)), both padawan and player monster Jedi act as quest guardians for a player Jedi - my assumption is this is intentional on the part of the original Jedi patch's author.

The unforeseen consequence of this is that, when patched into variants that generate hostile random player monsters anywhere outside the Quest or Astral - e.g. SlashTHEM and this variant, where mobileuser discovered this to what I'd imagine as great chagrin - killing a hostile Jedi that was not made hostile through any action of your own induces the massive alignment penalty associated with killing a quest guardian. Take that and add how much more alignment matters here due to the EvilHack influence, and I'm sure you can picture the disgust on past!Mobile's face.

Sadly, I don't have a PR to go with this - I'll leave that to cbus, who brought it to my attention.

**Comment by elunna** [comment]
I think it would be acceptable to just remove them from being player monsters - just having them in a different roles game vastly increases the chances of light sabers dropping (my opinion is lightsabers should be incredibly rare). But anyone have other ideas?

**Comment by hatcatter** [comment]
Sounds good to me. The other solution to fix it would be to add another jedi monster that isn't a guardian and make the guardians not spawn as player monsters. But keeping the sabers rare sounds good to me.

**Comment by elunna** [comment]
Is this why in SlashTHEM when you kill a padawan (like in the guild of disgruntled adventurers) you get a "you have a bad feeling about that..." msg?

Maybe "Jedi Trainer"?  Then Jedi can appear as player monsters but we'll remove padawan and jedi trainers?

**Comment by Umbire** [comment]
It is precisely the reason, yes.

**Comment by elunna** [comment]
Steps:
- [x] Removed Padawan from mplayers (they should only be quest guardians)
- [x] Add a new monster, Jedi Trainer (similar to Jedi maybe stronger)
- [x] Add tile, reorder tiles
- [x] Remove JEDI from quest guardians
- [x] Replace "jedi" in quest with "jedi trainer"
- [x] Update grudges to include jedi trainers vs storm troopers
- [x] Mixed in some Jedi into the quest for variety.
- [x] Fix the starting items for jedi, trainers, and padawans
- [ ] Add Jedi Trainer to quest guardians in role.c (not possible, only room for 1 guardian which is the padawan.
