### ISSUE TITLE
Dragon corpses eaten by hellminths in lawful quest

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#257]
Reported by mobileuser and janis.

With the new behavior of maggots from SpliceHack, they can "infest" corpses and create new monsters. The Lawful quest from slashem historically had maggots in one of the chambers, with another giant pile of dragon corpses. This creates a bit of a race to get to the dragon corpses before the maggots can eat them - or one can genocide maggots to ensure they don't infest them all. However, mobileuser discovered that genociding maggots resulted in them being replaced by hellminths - which are not supposed by be generated randomly.

It is possible this issue will be fixed when the order of monsters is fixed - so that a different w replaces maggots.

**Comment by mobi-leuser** [comment]
Or replace maggots with (eg) carrion crawlers in the des file?

**Comment by elunna** [comment]
Monster order now fixed so that hellminths are at the end of the w monster listings. Tested 2x genociding maggots and didn't see any hellminths, just rot worms.
