### ISSUE TITLE
Error: setting invalid material

### ISSUE THREAD

**Issue by transcendreamer** [elunna/hackem#268]
Shall I pick character's race, role, gender and alignment for you? [ynaq] (y)
setting material of garnet to invalid material 14  Program in disorder!
setting material of opal to invalid material 14  Program in disorder!
setting material of topaz to invalid material 14  Program in disorder!
...........
Unix HackEM Version 1.1.4-0 Beta - last build Mon May 29 14:30:23 2023
(91763da5b695d83ab47a977613cd0637e3be8908,branch:master).
..........
giant Undead Slayer

**Comment by elunna** [comment]
Easy to reproduce: Any giant undead slayer who starts with gems will trigger this. Use ctrl-P to see the error.

**Comment by elunna** [comment]
Problem: When the undead slayer inventory is being checked for objects to convert to silver - it's checking for things that pass is_ammo - which counts gems.

https://github.com/elunna/hackem/blob/5bcb61ca57fb75f338d951f4de2ea5429671490c/src/u_init.c#L2263

Solution: Add an additional check for gems, something like
`... || (is_ammo(obj) && (obj->oclass == GEM_CLASS && obj->otyp == SLING_BULLET)`
