### ISSUE TITLE
New idea: porting acid mage and electric mage from SLASHTHEM?

### ISSUE THREAD

**Issue by transcendreamer** [elunna/hackem#269]
If possible and if not against HACKEM dev philosophy.

**Comment by transcendreamer** [comment]
OK, brainstorming: 

- **chain lightning spell** (deals damage to several targets if they stay together tile to tile in any configuration, this will require to have algorithm for recursive check if current target has neighboring target in any 8 directions, effective for large groups of enemies like in confined spaces)
- **acid cloud spell** (create an acid cloud which inflicts damage to any creature without acid resistance each turn being inside the cloud and cloud stays for some time and be used as a strategic defense measure)
- acid mages could have some bonus from eating acidic corpses?
- electric mages could replenish their mana points from lightning?
- shocking any water-standing or swimming creatures with electricity?
- making shallow water and pool acidic?

Also I was thinking of 4 group of rival mage guilds (flame,ice,acid,electric) they are trying to dominate and beat each other. They set up ambushes and sometimes attack adventurer in small groups. So it will be important to have appropriate resistance or retreat. They berate adventurer, shout out curses and sometimes actually curse something in inventory. They could also block important levels and occasionally try to levelport adventurer away for the purpose of defending their territory (their level) actively opposing him/her.

Actually the same guild principle may be used to any roles/races, especially for special opposing pairs who may hate each other, e.g. priests against infidels and necromancers, or undead slayers against vampires. Probably it could be interesting gameplay if vampire adventurer is being hunted by undead slayers guild in some places? Also randomly wandering friendly person of the same guild (role/race) may sometimes help adventurer in fighting e.g. in towns.

Another examples of opposition: knights against rogues/pirates, monks against barbarians, yeomen against tourists, maybe even knights against samurais.

One more idea is implementing a special type of potion - elixir (like in Witcher RPG) which significantly improve magic or physical abilities for some longer interval of time, e.g. electric mage may cast longer chains of lightnings, acid mage may cast larger acid clouds, same principle for other spells distances and/or damage factors in melee. And this will make alchemy really very useful but it will require to think about recipes, e.g. dipping some corpses into some potions, etc. That will need some more time to elaborate....

**Comment by elunna** [comment]
This idea might be considered later post 2.0, but for now I'm moving it to our brainstorming doc. There are some other roles I want to try first so these would unfortunately be at the back of the line. I do appreciate the ideas though thanks!
