### ISSUE TITLE
Wishing for 100 stones in wizmode gives "program in disorder"

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#274]

**Comment by elunna** [comment]
Stone isn't an object, it's a material. Not a bug.

**Comment by elunna** [comment]
K2 had made a fix for this a while back so I'm not sure why it's happening, bf24a9b81.

An easy fix is to add this to alt_spellings in objnam.c:
{ "stone", ROCK },

Wishing for stone gives you a random number of rocks. Ideally though it should be handled as the above commit.

**Comment by hatcatter** [comment]
That would be awesome, I dunno why my brain insists on wanting to wish for 100 stones when in wizmode especially when rock is shorter to type :).

**Comment by elunna** [comment]
Nevermind, that was already in alt_spellings!  I think I'll still close this though, it doesn't really affect non-wizmode players.
