### ISSUE TITLE
Carrying cap inconsistency

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#284]
Reported by K2.

K2:  wearing GoP, carry cap is 1100 (str 25, con 18). when i mount my warhorse steed, carry cap drops to 1000. dismount, goes back up to 1100
(What role/race?)

**Comment by hatcatter** [comment]
To get carrying cap of 1100 gauntlets of power and hiking boots (to get from 1000 -> 1100) is needed.
The carrying cap for any ridden creature seems to be 1000 (tried with black dragon, pegasus, warhorse and a pony) and is not affected by hiking boots/GoP.

**Comment by hatcatter** [comment]
The increased carrying capacity from hiking boots is not handled in dNethack and the boots should not give increased carrying capacity when riding.
