### ISSUE TITLE
panic monsndx - could not index monster 

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#296]
Reported by oh6.

"1686601057 oh6: panic monsndx - could not index monster (561add9f2fb8: -1)" sacrificed a chickatrice corpse "Your sacrifice is consumed in a burst of flame!", and then "Oops..."

**Comment by hatcatter** [comment]
The ttyrec can be found on https://hdf-us.s3.amazonaws.com/ttyrec/o/oh6/hackem/ttyrec/2023-06-17.15:50:24.ttyrec.gz

**Comment by elunna** [comment]
This issue is caused by the monster selectors in god_gives_pet.

Chaotic demons are calculated using ndemon(u.ualign.type). 
Lawful minions are chosen using lminion();.
Neutral minions are chosen using neutral_minion(u.ulevel);.

If, for whatever reason, any of these functions returns PM_NON, the code proceeds to try and makemon using PM_NON, which triggers the crash.

**Comment by elunna** [comment]
Note: Also a likely bug in SpliceHack
