### ISSUE TITLE
Found with fuzzer: calculate_flankers

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#3]
Related to calculate_flankers - possibly a monster is out of bounds while checking if (MON_AT(xt, yt))
See this line: https://github.com/elunna/hackem/blob/0fe0d7a8b1a708d34461680f69dda33599e65658/src/mhitu.c#L5503

=================================================================
==10499==ERROR: AddressSanitizer: global-buffer-overflow on address 0x5555567b8f90 at pc 0x555555d06f6e bp 0x7fffffffdb80 sp 0x7fffffffdb70

READ of size 8 at 0x5555567b8f90 thread T0
    #0 0x555555d06f6d in calculate_flankers /home/lunatunez/hackem/src/mhitu.c:5503
    #1 0x555556242d19 in find_roll_to_hit /home/lunatunez/hackem/src/uhitm.c:303
    #2 0x55555624dde8 in hitum /home/lunatunez/hackem/src/uhitm.c:755
    #3 0x5555562494ad in attack /home/lunatunez/hackem/src/uhitm.c:579
    #4 0x555555ac70ed in domove_core /home/lunatunez/hackem/src/hack.c:1813
    #5 0x555555ab0ab5 in domove /home/lunatunez/hackem/src/hack.c:1516
    #6 0x555555862ec1 in rhack /home/lunatunez/hackem/src/cmd.c:5477
    #7 0x555555761bff in moveloop /home/lunatunez/hackem/src/allmain.c:798
    #8 0x5555563b4185 in main ../sys/unix/unixmain.c:353
    #9 0x7ffff7367082 in __libc_start_main ../csu/libc-start.c:308
    #10 0x555555758b0d in _start (/home/lunatunez/games/hackemdir/hackem+0x204b0d)

0x5555567b8f90 is located 8 bytes to the right of global variable 'ftrap' defined in 'decl.c:136:14' (0x5555567b8f80) of size 8
0x5555567b8f90 is located 48 bytes to the left of global variable 'youmonst' defined in 'decl.c:137:23' (0x5555567b8fc0) of size 216
SUMMARY: AddressSanitizer: global-buffer-overflow /home/lunatunez/hackem/src/mhitu.c:5503 in calculate_flankers
Shadow bytes around the buggy address:
  0x0aab2acef1a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acef1b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acef1c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acef1d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acef1e0: 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9
=>0x0aab2acef1f0: 00 f9[f9]f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0aab2acef200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acef210: 00 00 00 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0aab2acef220: 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x0aab2acef230: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acef240: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==10499==ABORTING

**Comment by gebulmer** [comment]
I think you're right, probably fixed with an `isok(x,y) && MON_AT(x,y)`

if you want to be radical you can redefine MON_AT to include isok, I think some 343 variants have done that
