### ISSUE TITLE
paranoid pet-travel can choke pets

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#303]
if you fast travel using _ and have a leashed pet you choke the pet constantly.

**Comment by elunna** [comment]
Is this really a bug?  I always thought _ meant "running" which would logically choke pets.  

Is there a similar issue in vanilla?

**Comment by hatcatter** [comment]
Yeah vanilla has the same issue. I feel that solving this is "elegant" instead of manually having to wait for your pet to show up all the time. Not sure how hard this would be to solve though.

**Comment by Umbire** [comment]
I'm having a similar trouble minus leashes where my pet's pathing seems to elect for a literal beeline to me - as in, if there's any walls between us, pathing around them never occurs and as a result the pet becomes "stuck" constantly.

**Comment by elunna** [comment]
Closing this. I think the behavior of leashed pets is fine as is. The autotravel seems to work fine most of the time.

Also, the behavior of pet pathing is the same as vanilla nethack, unless there is a recent commit in evilhack or vanilla I'm not aware of. Please post it so we can update.
