### ISSUE TITLE
Modify Rodney's ability to steal quest artifacts.

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#310]
In dnethack the wizard can't steal any quest artifacts, in hackem and 3.6 he can steal all quest artifacts, in 3.4.3 he can steal only your own quest artifact

It might really benefit races like Tortle and Giant if we go with the dnh implementation, or at least the 343 version.

**Comment by elunna** [comment]
Additional side-effect - removing MR from Xanathar's ring isn't such a big factor for those races.

**Comment by elunna** [comment]
Looking at the devteams reasoning for the change to the theft of artifacts, I think their reasoning was sound and we'll keep it as is.

**Comment by elunna** [comment]
Actually... bhaak from UnNetHack recently made some commits that allow this to come to fruition: 
https://github.com/UnNetHack/UnNetHack/commit/b21364d4f4e55edb961d204d3145c09fa11204db
https://github.com/UnNetHack/UnNetHack/commit/e4be6175e499134f08249d36a09291ea6f0d42a3
https://github.com/UnNetHack/UnNetHack/commit/6853329a9c9f21499b4e8624336780b48783446c

These have been merged in and this issue is actually completed as intended!

**Comment by mobi-leuser** [comment]
allowing the Wizard to steal Dragonbane, Magicbane etc. is.... well....

**Comment by elunna** [comment]
Better grease it up!

**Comment by hothraxxa** [comment]
Better grease it up? Grease what up? Grease does not affect theft.

**Comment by mobi-leuser** [comment]
hothraxxa it does. Funnily enough people were saying in the evilhack channel that it's not much use, because the grease keeps dissolving.

**Comment by hothraxxa** [comment]
Is this an evilhack thing? Grease has always been frustrating because 50% of the time it dissolves.

**Comment by elunna** [comment]
hothraxxa: Yes, these commits were patched from evil to hackem. These make greased items harder to steal.

https://github.com/elunna/hackem/commit/0967945f975fd9c79b567defd2f3a1400c865340
https://github.com/elunna/hackem/commit/a0027f99be588a3226defcafaec90831d3f1b25f

Also - I'd like to mention that Rodney doesn't have the same nastiness as in evilhack. Rodney only gets an amulet of magic resistance to 1 in 13 times (changed from Evil where it was 50%). So if you have a couple wands of death or something equally good, he should usually be dead pretty quick.

**Comment by mobi-leuser** [comment]
Rodney can cast a reflection sphere though. I've had to really fight him a couple of times.

**Comment by elunna** [comment]
You can cancel monster reflection with a wand of cancellation which is pretty neat, I just tested it out

**Comment by mobi-leuser** [comment]
ah, nice tip! and there are also people saying it's very easy to keep missing Rodney with a wand death (he has low AC)

**Comment by elunna** [comment]
My own memory fails me - there was a change so that Rodney never starts with the amulet of MR - it's an amulet of life saving instead lol.
