### ISSUE TITLE
Player vampire attacks

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#318]
Re-enable 2-twoweaponing for roles that allow it.

Also, tweak the drain life damage a bit so the vampire gains more life on average. Potential scale with the player's level.

**Comment by hatcatter** [comment]
Also update the wiki about twoweaponing since it specifically mentions that vampires are restricted in two-weaponing.

**Comment by elunna** [comment]
Re-enabled the vampire two-weaponing in commits d0b671b8d and 8a8e1e70a
