### ISSUE TITLE
Marauder's Map invoke needs artifact detection

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#327]
The original SlashTHEM implementation is here: https://github.com/Soviet5lo/SlashTHEM/blob/d828e641d341175b5829bef070879bb163c7f636/src/detect.c#L596C26-L596C26

It is a duplicated version of object_detect. I'm hoping we can weave in the artifact detection instead of copy-pasting the artifact_detect function.

**Comment by elunna** [comment]
Too difficult to implement.

**Comment by hatcatter** [comment]
"Just pretty much duplicate the object_detect function and make it artifact_instead"
