### ISSUE TITLE
Slithering through iron bars in sokoban does not count as cheating

### ISSUE THREAD

**Issue by hatcatter** [elunna/hackem#365]
When slithering through bars in sokoban does not count as cheating.
Example:
Load level "Sneak Preview" (soko2-15) and slither from the L room to < in the shape of a snake.
https://nethackwiki.com/wiki/Sneak_Preview

Thanks to Umbire for suggestion having a look at this!

**Comment by hatcatter** [comment]
Phasing through bars is also possible but walls resist phasing.

**Comment by elunna** [comment]
Slithy monsters are blocked from moving through sokoban iron bars.
https://github.com/elunna/hackem/blob/d7c2ee43ba21ca4880e20fcdb7cadc9cb23ea5f7/src/hack.c#L748
