### ISSUE TITLE
Silver scaled armor does not help vs lightning bolt from trap

### ISSUE THREAD

**Issue by hatcatter** [elunna/hackem#373]
Mobileuser got blinded by a lightning bolt from a magic beam trap but probably had it working from blinding in a poison cloud.

**Comment by mobi-leuser** [comment]
Specifically, hackem wiki says blinding res is a secondary effect for silver-scaled armour

**Comment by hatcatter** [comment]
Info on https://nethackwiki.com/wiki/Hack%27EM#Dragons_and_Dragon_Scales

**Comment by elunna** [comment]
Also: "giant knocked me back and then couldn't see his reflection in my silver scaled armor"

**Comment by elunna** [comment]
Fixed the last comment in 11bd61baf

**Comment by mobi-leuser** [comment]
btw, "giant knocked me back and then couldn't see his reflection in my silver scaled armor" was not a bug report, just a funny message ;-)
