### ISSUE TITLE
Infidels are missing an entry in the guidebook

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#383]
I was able to come up with stuff for Jedi, Pirates, and Convicts, but my inspiration has been lacking for infidels - maybe someone who has played them can pencil something moving.

An example of the length and style is here:
```
    Knights are distinguished  from  the  common  skirmisher  by
          their  devotion  to  the ideals of chivalry and by the surpassing
          excellence of their armor.
```

**Comment by mobi-leuser** [comment]
Infidels start with the Amulet of Yendor and initially need to return it to Moloch. They are weldproof and masters of fire and magic. An Infidel will soon be hunted by agents and champions of the other gods who want the Amulet...

**Comment by elunna** [comment]
Sweet, couple revisions but how about this?

Infidels start with the Amulet of Yendor and initially need to return it to Moloch. They are masters of fire and magic. On their quest, an Infidel will be hunted by agents and champions of the other gods who covet the Amulet...

**Comment by mobi-leuser** [comment]
- you will be hunted much sooner than the quest
- weldproof is a unique ability of Infidels, why leave that out?

**Comment by elunna** [comment]
Oh, I didn't mean the quest literally, more like "on your mission" lol. I'll just stick with your version :)
