### ISSUE TITLE
Races with armor restrictions can receive unusable armor from their god

### ISSUE THREAD

**Issue by Ardub23** [elunna/hackem#385]
Centaurs, tortles, and giants are unable to wear certain kinds of armor, but there's no check for this in mk_artifact(). This can result in, for instance, the rather disappointing outcome of receiving Whisperfeet as a centaur. I don't believe that the possibility of polymorphing into a form that can wear armor is enough to make these appropriate gifts; the same could apply to material hatred, but mk_artifact checks for that anyway.

**Comment by elunna** [comment]
This is correct, thank you for the report!

I think this should be relatively easy to fix. I also noticed possible issues with banes being gifted to the wrong races too so I'll see if we can tidy that up.

**Comment by elunna** [comment]
Fixed! Let me know if any other weird cases for gifts come up.
