### ISSUE TITLE
does killing your pet reduce luck?

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#388]
hothraxxa noticed no reduction in luck after killing 3 gas spore pets. Saccing at an altar didn't produce any 4-leaf clovers.

**Comment by elunna** [comment]
Reproducing attempt 1: a level 15 lawful male human Undead Slayer.
I killed my tame dog, got a -1 luck penalty.
I also killed a tame gas spore, -1.

Reproducing attempt 2: a level 15 unaligned male giant Infidel.
Killed starting pet, -1. Killed a summoned tame dog, -1.

Reproducing attempt 2:
Wished for uncursed luckstone. Luck = 3
Killed tame dog, luck went to 2.

I wasn't able to reproduce this quickly, can I get some more info?

What race/role/alignment were you?
Did you have any luck items?
Was your luck at max/min (-13 or 13)?
Did you know your exactly luck (was it wizmode?)
Where did the gas spores come from (confused stinking cloud or maybe neutral quest?)
Did you have the post-quest luck boon in effect?

**Comment by hothraxxa** [comment]
i'm a gnome healer with a luckstone. i only know my luck from enlightenment (extremely lucky). killed three pets. gas spores on the neutral quest, stepped on a magc trap, tamed some of them, hit one and they all blew up of course. in my defence i was blind and didn't know i'd tamed them. the explosion also killed my regular pet. i felt intense guilt three times (so -45) but was still piously aligned. i was probably way over +45 alignment though. the luck thing is hard to explain, went back to the altar to adjust it, could not get any four-leaf clovers although they were good corpses for that. i think one was a rothe for example. i don't see how i was still extremely lucky but maybe that's what it reports when you're at +10?

**Comment by elunna** [comment]
At 10 or greater luck you are extremely lucky. My guess is that your god was angry at you? Because until you pacify them you won't get any four-leaf clovers.

**Comment by mobi-leuser** [comment]
If your god is angry with you, you will get "god seems (slightly) mollified" messages. Also, killing a pet doesn't anger your god, it "only" reduces luck by 1 and alignment by -15.

**Comment by hothraxxa** [comment]
hermes was fine. i did not get any boons and my sacrifices just disappeared in a cloud of smoke.

**Comment by mobi-leuser** [comment]
Original question was answered (killing your pet does reduce luck), closing.
