### ISSUE TITLE
Arrows don't work for me

### ISSUE THREAD

**Issue by YesLaching** [elunna/hackem#411]
I tested it with a human ranger and with an orc ranger. Neither firing arrows with a bow, nor throwing them by hand works. They never hit.
I really like rangers, hopefully it's not a bug but my incompetence...

**Comment by elunna** [comment]
Which version are you playing? Did you download/build it from github or are you playing it on hardfought?

**Comment by hatcatter** [comment]
We had a bug like that but it was in one of the in-between-versions for testing between 1.1.4 and 1.2.0 (should not be in 1.1.4 or 1.2.0).

**Comment by hatcatter** [comment]
The bug seems to show up first in 1.1.4b

**Comment by YesLaching** [comment]
> Which version are you playing? Did you download/build it from github or are you playing it on hardfought?

1.1.4-1 Beta from 18. July

**Comment by hatcatter** [comment]
It is fixed in the current version (and verified that just got installed on HDF) so I am closing this issue.
Thanks for reporting!
For details [601d83c6ccd72e4f7c6b92d8a8fa1490f03dc5d5](https://github.com/elunna/hackem/commit/601d83c6ccd72e4f7c6b92d8a8fa1490f03dc5d5) caused the issue.
