### ISSUE TITLE
peaceful monkey helps fat cat pet to flank a hostile wood nymph

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#418]
My fat cat pet was attacking a wood nymph and got flanking assistance from a peaceful monkey, that looks like a bug?
Earlier, a shopkeeper gave flanking assistance to my cat when it was attacking a Draugr, but that one makes sense because of the zombie grudge.

**Comment by elunna** [comment]
Thanks mobileuser!  Yes I was able to figure out the problem and make a bit of improvement to this. The grudge bit was a good observation, so now we're using that as the determining factor.
