### ISSUE TITLE
invoking Marauder's Map

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#419]
It looks like the new invoke of Marauder's Map also works like a scroll of magic detection.
Not only that, but all enchantments on all weapons and armor on the level get revealed.
Nice features! ;-)
So far no artifacts detected, but I've only invoked it on 2 levels, will add a comment when it detects an artifact.

**Comment by mobi-leuser** [comment]
It also detects the charges on wands.

**Comment by elunna** [comment]
Thanks for the report!

**Comment by hatcatter** [comment]
ASAN also blows up

**Comment by elunna** [comment]
> ASAN also blows up

Please attach the asan output, just saying it blows up doesn't help me.

**Comment by hatcatter** [comment]
I can't seem to reproduce it now for some reason.
But it blew up when invoking it.

**Comment by hatcatter** [comment]
After switching to hints/linux (from linux-debug) and then back to hints/linux-debug the ASAN issue just disappeared.
