### ISSUE TITLE
pirate pets and treats

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#420]
In my first 1.2.0 pirate game I started with a parrot and bananas.
In my second pirate game I started with a monkey and kelp fronds.
Did the treats get switched somehow?

**Comment by mobi-leuser** [comment]
Ugga-Ugga does seem to like the kelp fronds. Squawk didn't care much for the bananas.

**Comment by elunna** [comment]
In splice and dnethack these items are just randomized, actually I'm not sure there is a way to query what pet you have to match it up.  But I can probably get the parrot to eat bananas! According to some quick googling, they do eat them.

**Comment by mobi-leuser** [comment]
Ah ok! Yeah, the parrot did eat bananas when hungry. Just not as a treat.
