### ISSUE TITLE
Vampiric hero can still wither

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#424]
Vampirics are supposed to have wither resistance, but they can still wither. Reported by hothraxxa.

**Comment by elunna** [comment]
Do we have any more info or how I can reproduce this?  A brief look though the wither attacks and I see they all have exceptions for undead or vampshifters so I'm not sure where to start.

**Comment by elunna** [comment]
Nevermind - I am able to reproduce it with a vampiric race. :)
