### ISSUE TITLE
Transmogrify can give artifacts glitch material "hackdir"

### ISSUE THREAD

**Issue by Ardub23** [elunna/hackem#425]
To recreate this, use wizard mode to wish for an artifact and a large number of transmogrify scrolls, and use the scrolls on the artifact. There is a very small chance that the artifact's material will change to something the game calls "hackdir", which is practically weightless. The hackdir Helm of Hermes is reported as having "Effective AC 1528853281 (from material)" and sets AC to −128 when worn. The material doesn't seem to give weapons any crazy properties.

To make it easier to notice when the artifact becomes "hackdir", you may want to set MSGTYPE=stop "\*hackdir\*" or use curses with perm_invent. Also, don't wizidentify the artifact, because that hides its material.

**Comment by elunna** [comment]
Awesome, thanks for the report!
