### ISSUE TITLE
Ludios 2 has no upstairs

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#429]
hothraxxa descended from Ludios (level 14) to Ludios 2 (level 23). There were no upstairs.
He had to branchport out. He also says the level didn't look like the DES file (yoy will have to ask him for details on what it looked like).

**Comment by hothraxxa** [comment]
The des files I looked at doesn't have a ludios 2 from any variation of Fort Ludios. I wound up in a large room with swamp in the middle and a row of water cells. The north and south walls had a series of one cell closets spaced one cell apart. Many but not all had doors, some open. The monsters were appropriate for a dl23 swamp and I got slimed. There was a door in the middle of the west wall that led to a barracks full of soldiers. There there was a corridor to a room on the south and that room had another corridor to a room full of potions, one per cell. There was a hidden door on the east wall from there that opened to a corridor that ended up in a bathroom, or at least a room with a toilet and a sink. There was also a corridor behind a secret door in the north wall of the barracks that went to a tiny three cell room. There were no stairs up anywhere and searching did not  find any more secret doors. (I did not have a scope.)  I tried digging down but after i made a pit the floor was too hard. I also dug to the walls in all four directions. I finally used magic mapping but it did not show anything new. The a zombie dragon showed up and I branchported out.

**Comment by elunna** [comment]
Well that is a big OOPS!  Thanks guys....

hothraxxa, the des file for the dungeon underneath ludios is not the same as for ludios, it's ucastle.des (used to be "under castle" but now it's under ludios).

**Comment by elunna** [comment]
This is fixed now - I *think* it breaks saves so it will have to wait until next release, so that might have to come soonish :P

**Comment by elunna** [comment]
> Is it possible to levelport out of ucastle.des? Asking for a friend without branchporting....

Yes I think so, the level is marked as noteleport, but that should just be for wands/scrolls, etc.

**Comment by mobi-leuser** [comment]
I noticed that when I levelported to level 1 from Ludios 2, I ended up on level 1 of the dungeon instead of Ludios 1.

**Comment by elunna** [comment]
If you levelport to 1 it's usually level 1 of the main dungeon, unless you are in a portal'ed branch like the quest.
