### ISSUE TITLE
Wielding stakes makes all thrown weapons act like stakes for killing vampires 

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#434]
Noticed by Umbire

**Comment by Umbire** [comment]
This did need to be addressed before too long honestly - having it result in a 3-shot of my quest nemesis via thrown silver dagger is just stupid.

Funny yes, incredibly so, but also stupid.

In any case, this was only for thrown daggers specifically (the only such projectile my current Und's used) - I don't know if it extends to other thrown/shot projectiles as well.

**Comment by elunna** [comment]
Yep!  Easy fix luckily.
