### ISSUE TITLE
bug: damage calculation doesn't use slash'em style flat damage

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#444]
A question about damage calculation.
I'm wielding a +6 Disrupter with +30 vs undead.
I hit a ghast, with AC 9 and HP 31. I pretty much expect to one-shot it.
Instead it still has 12 HP left after 1 hit.
How is that possible?

**Comment by mobi-leuser** [comment]
still curious about this one :-)

**Comment by mobi-leuser** [comment]
it looks like somewhere in the commit history the flat damage commit got undone again:
    if (spec_dbon_applies) {
        dbon = weap->attk.damd ? rnd((int) weap->attk.damd) : max(tmp, 1);
still searching where...

**Comment by mobi-leuser** [comment]
this commit broke the flat damage:
https://github.com/elunna/hackem/commit/8e6b898577ec4fbefd0881e162adaf936e6898d9

**Comment by elunna** [comment]
Ah thanks, one of the new evil patches I see.
