### ISSUE TITLE
Draugr visible with esp

### ISSUE THREAD

**Issue by hothraxxa** [elunna/hackem#451]
Darugrs are supposed to be zombies but I can see them with esp.

**Comment by elunna** [comment]
I did some brief research, apparently draugr might have physical bodies, so this might be valid. Not sure though, any other thoughts?

https://en.wikipedia.org/wiki/Draugr

Might be neat if they are the only undead to be visible by ESP too...

**Comment by hothraxxa** [comment]
I am pretty sure they are the only undead to be visible with ESP. While this is nice, it seems inconsistent. All zombies have bodies, they just don't have brains. That's why we can't see them with ESP.

**Comment by k21971** [comment]
Any monster flagged as M1_MINDLESS won't be seen via ESP. Without actually looking in monst.c, I'm betting Draugr aren't flagged as such. Given what they are, that's probably fine. They're more akin to a barrow wight than a zombie.

**Comment by elunna** [comment]
I don't think they are technically zombies, from the wikipedia article they seem to be something in between. They might even be eligible to be marked as magical. And yes, the mindless tag is missing, not sure this was the original intention from SpliceHack.

I'm not really familiar with the draugr from anything I've read - SpliceHack was my first encounter with them - so please refer me to other sources if there is something with more compelling.

**Comment by hothraxxa** [comment]
I'm fine with the way it is. I just thought it was inconsistent.
