### ISSUE TITLE
Instakill text for thrown Sting

### ISSUE THREAD

**Issue by Umbire** [elunna/hackem#453]
Minor issue - throwing Sting at an orcish monster and landing the instakill text produces the same text as if you had directly attacked that monster in melee. Below, message history from me doing just that to an orc shaman: 
![putty_6iZx8qIklm](https://github.com/elunna/hackem/assets/56782189/a15a3462-595b-46c2-8bf2-eb7a48784af5)
The text for an instakill by thrown Sting (or any applicable monster-hating artifact) should at least reflect that it was thrown.

**Comment by elunna** [comment]
Also reproduced in EvilHack.

**Comment by elunna** [comment]
@k21971 Also in evilhack - I'm finding it hard to be motivated to do anything about this lol - so I'll just link you to it and hope terrapin fixes it :D

**Comment by k21971** [comment]
I'll have a look.

**Comment by elunna** [comment]
I think this is fine for now - I might revisit it in the future.
