### ISSUE TITLE
Cannot wield crossbow while wearing a shield as a giant

### ISSUE THREAD

**Issue by Umbire** [elunna/hackem#455]
...despite wielding a mattock just fine. Is this a quirk/bug, or are crossbows intended to be two-handed no matter what? If the latter is the case, the message should probably be changed to reflect that. Pictured below, the crossbow is in the alternate weapon slot and I can't swap weapons to it with the worn dwarvish roundshield:

![image](https://github.com/elunna/hackem/assets/56782189/515e39da-4727-499a-96aa-82325a135ae8)

**Comment by elunna** [comment]
@k21971 I think this is also in EvilHack - thoughts?
