### ISSUE TITLE
Luck Blade should have Luck on carry

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#460]
In Slash'EM, Luck Blade confers Luck when carried, but at the moment it needs to be wielded.

**Comment by elunna** [comment]
Not able to reproduce - it grants luck when carried already.

**Comment by mobi-leuser** [comment]
That's weird, I looked at the code and the luck was encoded as on wield.

**Comment by mobi-leuser** [comment]
That's also what shows in the pokedex. I installed Hack'EM locally today, maybe I will try tomorrow...

**Comment by elunna** [comment]
It seems to be the same with the other luck weapons, Tsurugi of Muramasa also has it in the same place. I see now the confusion with the pokedex though. I'll have to see if it can be switched to the other slot without any consequences...

**Comment by mobi-leuser** [comment]
I think I saw it in the other slot in another repo... maybe Slash'EM
