### ISSUE TITLE
revert "Greater chance of hostile minion appearing when converting an altar"

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#461]
See:
https://github.com/k21971/EvilHack/commit/69aa782d963fc6c7ac700d42f918f23d76bc314b

This was inherited from evilhack and is very fitting for evilhack, but in the spirit of de-eviling hackem it would be nice if this was reverted :-)

**Comment by elunna** [comment]
I checked SLASH'EM, and there is a very similar mechanic... but it's meaner and can summon 2 elementals. The evilhack calculation is a bit more complicated but probably more fair. I think we'll just keep it as is.

**Comment by mobi-leuser** [comment]
:-(
