### ISSUE TITLE
Dipping objects into fountains 'Y' or 'y'

### ISSUE THREAD

**Issue by transcendreamer** [elunna/hackem#463]
Sometimes 'y' key works OK, sometimes 'Y' key is needed.

**Comment by transcendreamer** [comment]
Windows HackEM Version 1.2.0-0 Beta - last build Mon Jul 31 20:17:00 2023 (x64).

**Comment by elunna** [comment]
I'm not able to reproduce this. 

Do we have a specific item involved or can you reproduce it with a certain set of steps?

**Comment by transcendreamer** [comment]
I will investigate. Unfortunately that save-file is lost, I need some time...

**Comment by elunna** [comment]
Could it be a font issue?

**Comment by transcendreamer** [comment]
It was definitely a fountain in the Mines and the object was some cursed ring, I'm testing it right now. 

Sometimes dipping just doesn't produce any message - and I've got series of unsuccessful dippings - that's why I was thinking it doesn't work at all - and it was my mistake to connect it to pressing 'y' or 'Y'.

Sorry for false alarm.

**Comment by transcendreamer** [comment]
I believe now it was my mistake, the issue may be closed.

Suggestion: probably some textual message may be added in case of unsuccessful dipping to provide feedback for dipping action.

**Comment by elunna** [comment]
Ok that makes sense.  I think a different forkor 3.7 might have done a patch like that. I'll take a quick look...
