### ISSUE TITLE
BUG: Necromancer undead pet still betrays

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#464]
According to the wiki:
"Undead will never betray Necromancers"

However, my ghoul mage pet turned on me.

**Comment by elunna** [comment]
I just want to double check, did you get one of these messages?

"Your ghoul mage turns on you!"
or You_feel("uneasy about your ghoul mage."

Or did your ghoul mage just go feral when left alone for a while?

**Comment by mobi-leuser** [comment]
"Your ghoul mage turns on you!"

That one!

**Comment by mobi-leuser** [comment]
Yay, thanks!

**Comment by elunna** [comment]
Yup, my bad - took me a bit to see the bad parentheses but luckily an easy fix.
