### ISSUE TITLE
Price for scroll identification too high?

### ISSUE THREAD

**Issue by transcendreamer** [elunna/hackem#467]
Maybe it's not an issue but a feature, but, this is what I see in the bookstore: shopkeeper offers scroll ID for 210z to my lawful adventurer, where I can just buy scroll of ID for just 20z, quite a great difference!

From the game balance POV scrolls of ID always were very cheap in Nethack anyway...

**Comment by elunna** [comment]
The difference is that the shopkeeper service is an infinitely reuseable resource - so it has to be expensive so it's not just abused. I like to think of it as a money sink for when you start to get extra cash, especially for the more expensive services like weapon enchanting or tinkering.

**Comment by transcendreamer** [comment]
OK! It makes sense!
