### ISSUE TITLE
Vanishing nickelpede

### ISSUE THREAD

**Issue by Umbire** [elunna/hackem#476]
I whistled a pet nickelpede over near a corpse, and it simultaneosly hid under the corpse and ate it, disappearing from view - luckily I searched and found it as normal. This probably applies to most hiding monsters that use objects.

**Comment by elunna** [comment]
If you didn't get a "program in disorder" message or crash, this should be a non-issue. There are panic checks for monsters that are impossibly hidden so I think it was just under some grass.
