### ISSUE TITLE
Feature request: Make the current shortcut for kicking a config option

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#477]
See:
https://github.com/elunna/hackem/commit/01e4a77b8b7c70b8df0997dfff9a397c73aee1e5

This messes with running using ctrl-[yuhjklbn] for people using vi-keys.
More than one person has mentioned this, it would be nice and help the popularity of hackem if this could be made into a config option.

**Comment by hothraxxa** [comment]
What would be nice is the BIND options seen in Gnollhack.

**Comment by k21971** [comment]
Binding keys is not a gnollhack specific feature. See https://nethackwiki.com/wiki/Binding_keys

**Comment by hothraxxa** [comment]
Fair enough. It's the only variant I've used it in. Does this mean Hackem already supports that?

**Comment by elunna** [comment]
Done!
