### ISSUE TITLE
About vampires again (new ideas)

### ISSUE THREAD

**Issue by transcendreamer** [elunna/hackem#492]
I was playing as vampire over and over and I should say it's cool but I still would like to share some new ideas to make it more atmospheric / feeling of vampiric adventure.

Basically it's cool that vamps now don't need to drain corpses as it was in original Slash'em, but the gameplay still lacks some peculiar traits and challenges of being a vampire because of auto-biting.

I love the idea that only living creatures could be appropriate sources of blood although I'd like to suggest rebalancing/refactoring vampires' gameplay allowing them to bite only victims in stunned / dazzled / paralysis / blindness / sleeping state or if the vampire has displacement/invisibility/stealth and the victim has not detected vampire's position yet.

Vampire must not be in active fight to feast on victims, and to compensate hunger and HP drawdown between fights - amount of blood (HP and nutrition value) sucked from single victim may be increased a bit - it's a question of balance tweaking of course.

Biting may be implemented e.g. as #monster ability and require some time to complete without interruption (like eating).

I believe this would add more interesting gameplay situations:

- sneak up and bite (using ring of stealth / invisibility)
- zap a wand of sleep and bite them
- apply expensive camera to blind and bite
- wear cloak of displacement to mislead about actual position and bite
- step into zoo full of sleeping monsters and bite them / draw blood from them
- other enemies nearby may occasionally detect vampire and attack him/her
- kill nearby enemies before sparing one victim for safe uninterrupted blood-sucking
- retreat from large group of enemies seeking for single victim of appropriate level
- higher level monster are harder to bite and have higher probability of resisting biting and fighting back
- when vampire gets XP and level-up it becomes a bit easier to bite monsters of higher base level

I hope you find my humble ideas worth reading.

**Comment by hothraxxa** [comment]
As you know, I've also played a lot of Hackem vampires. If you implement this, I think you should also add some chance of gaining intrinsics. Vampires essentially only have three ways to gain intrinsics: crowning, gifts from a god, and poly into a form that can eat. Crowning and gifts do not prvide things like disintegration resistance or teleportitis. Eating requires a lot of careful prep (not to mention a tinning kit) and is not always successful. In all my games, I've never been disintegration resistant or had teleportitis. I once polyed into an elven king and ate four tins of nymph and two of leprechaun and still didn't get teleportitis.

**Comment by transcendreamer** [comment]
Also I was thinking to suggest the blink ability / technique to vampires (e.g. see Vampyr 2019 game).

**Comment by elunna** [comment]
Thank you for the ideas transcendreamer!  It sounds similar to how rogue's get backstab damage - I'll have to think on it :)

hothraxxa: Good news - I think the upcoming revamp of properties will address some of the intrinsic problems vampires have had.
