### ISSUE TITLE
Monster generation rate status

### ISSUE THREAD

**Issue by transcendreamer** [elunna/hackem#508]
Self-knowledge produces among other info: **monster generation rate as #.##x** - which looks too technical and probably should not be shown to player in such extraordinary precise way? Compare to something like "doomed" status like in ADOM with higher than normal monster spawning. https://ancardia.fandom.com/wiki/Doomed - Because #.##x is too much kind of internal game data...

**Comment by elunna** [comment]
Oh yea, that is kind of funny. I was thinking of removing the turn count factor (after 50000 turns the turn count starts to factor in) so this is a good nudge to do that.
