### ISSUE TITLE
Game crash upon *gifted* gremlin meeting water

### ISSUE THREAD

**Issue by Imanity0** [elunna/hackem#513]
Just had the Orc temple variant of fake mine's end. Was gifted a tame gremlin after a few sacrifices. Used a magic whistle to call it to the downstairs. The gremlin was ported to the water, replicated and my game crashed. Was able to recover, but the gremlin is gone

**Comment by elunna** [comment]
This was fixed in commit 24565609c, however it wasn't pushed live to hardfought yet. I will see about getting a hotfix up for it. Thank you!
