### ISSUE TITLE
Duplicate rot timer with BoH

### ISSUE THREAD

**Issue by Imanity0** [elunna/hackem#515]
#302 is also a problem for bags of holding, not just locked containers
Killed a bunch of zombies, put them into a bag of holding on the ground and got this message shortly after putting the 8th one inside:
"Attempted to start duplicate rot_corpse timer, aborted
Program in disorder!"

As it happened:
![2023-10-25 05_07_20-eu hardfought org - PuTTY](https://github.com/elunna/hackem/assets/148825688/3cc73372-3b6d-4c28-b1e9-d59b3a7ec3fa)

Post-save/reload
![2023-10-25 05_17_54-eu hardfought org - PuTTY](https://github.com/elunna/hackem/assets/148825688/0d73f8bb-5a4d-448c-b212-c9c1b00de857)

**Comment by elunna** [comment]
Ah ok - I think the fix covers both scenarios. The current fix isn't live on hdf yet.

**Comment by elunna** [comment]
Fixed in https://github.com/elunna/hackem/commit/da9b53d2a627311e36f0c7f8e63d33238fe56cab
