### ISSUE TITLE
Cannot open file "1000lunatunez.-128" for level -128 (errno 2).

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#69]
Reported by cbus while attempting to save on level 3

**Comment by elunna** [comment]
PREFIX=$(HOME)/.local
HACKDIR=$(PREFIX)/games/lib/$(GAME)dir

**Comment by gebulmer** [comment]
is this easily reproducible? is it possible you have more than 128 dungeon floors? (if e.g. all dungeons roll max number of floors)

**Comment by elunna** [comment]
> is this easily reproducible? is it possible you have more than 128 dungeon floors? (if e.g. all dungeons roll max number of floors)

No, I've only seen this reported by cbus.  It is possible - I've been near the limit of 128, even after I disabled the Ice Queen branch, but still see hints/sounds on the level the portal shows up on. So I'm not sure that branch is 100% gone. I did prune down some other levels today just to be sure.

**Comment by elunna** [comment]
Can't reproduce.
