### ISSUE TITLE
Create database lookups for all items/monsters

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#92]
- [x] Weapons
- [x] Armor
- [x] Spellbooks
- [x] Food
- [x] Tools
- [x] Gems
- [x] Gray stones
- [x] Potions
- [x] Scrolls
- [x] Wands
- [x] Rings
- [x] Amulets
- [x] Player monsters are broken
- [x] flame mage - from Game of Thrones?
- [x] necromancer - something from LOTR?
- [x] undead slayer - Something from buffy?
- [x] yeoman
- [x] Alchemy recipes are listed, and shown under each potion lookup.
- [x] Smoky potion
- [x] Item upgrades via Potion of Gain Level: "upgrading" or "upgrades" for a full list)

Role based info
- [x] multishot penalties
- [ ] Cover weapon/armor based first.

[x] Bonuses/penalty to bow tohit

**Comment by Hash56** [comment]
Will it include an info summary on the current race and role we're playing? (maybe accessible through CTRL+ X). In variants I never know whether to read the vanilla wiki article first, then the variant's version, then the changelog so I LOVE this initiative!
